### ISSUE TITLE
Problems regarding different eslint configs

### ISSUE THREAD

**Issue by seba90** [code-iai/iai-web-build-tool#2]
I wanted to remove the rule block in the project's eslint config.
https://github.com/code-iai/iai-web-build-tool/blob/5314b11f1ec0d14ca09a6127a8c99f6560d6331b/.eslintrc.json#L9

However, if I remove the block, the linter throws and indenting error.
This means, we need to update the openease lint config which we are providing or we need to update the current code based on our current openease lint config

**Comment by navidJadid** [comment]
Block removed, linter still working.
